apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---    
apiVersion : apps/v1
kind: Deployment
metadata:
  name: rineshkumarpythonrediscomposeapp 
spec:
  replicas: 1
  selector:
      matchLabels:
        app: rineshkumarpythonrediscomposeapp
  template:
    metadata:
      labels:
        app: rineshkumarpythonrediscomposeapp 
    spec:
      containers:
        - name: rineshkumarpythonrediscomposeapp 
          image: mrrkacr.azurecr.io/rineshkumarpythonrediscomposeapp
          ports:
          - containerPort: 5000
          env:
          - name: REDIS
            value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: User facing service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rineshkumarpythonrediscomposeapp        