apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---    
apiVersion : apps/v1
kind: Deployment
metadata:
  name: rineshkumarpythonrediscomposeapp 
spec:
  replicas: 1
  selector:
      matchLabels:
        app: rineshkumarpythonrediscomposeapp
  template:
    metadata:
      labels:
        app: rineshkumarpythonrediscomposeapp 
    spec:
      containers:
        - name: rineshkumarpythonrediscomposeapp 
          image: mrrkacr.azurecr.io/rineshkumarpythonrediscomposeapp
          ports:
          - containerPort: 80
          env:
          - name: REDIS
            value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: rineshkumarpythonrediscomposeappservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rineshkumarpythonrediscomposeapp        