apiVersion : apps/v1
kind: Deployment
metadata:
  name: rineshkumarpythonrediscomposeapp 
spec:
  replicas: 1
  selector:
      matchLabels:
        name: azure
  template:
    metadata:
      labels:
        app: rineshkumarpythonrediscomposeapp 
    spec:
      containers:
        - name: rineshkumarpythonrediscomposeapp 
          image: mrrkacr.azurecr.io/rineshkumarpythonrediscomposeapp
          ports:
          - containerPort: 5000