apiVersion: v1
kind: Service
metadata:
    name: rineshkumarpythonrediscomposeapp
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: rineshkumarpythonrediscomposeapp