apiVersion: v1
kind: Service
metadata:
    name: rineshkumarpythonrediscomposeapp
    labels:
        name: rineshkumarpythonrediscomposeapp     
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: rineshkumarpythonrediscomposeapp